protocol_version : v2
name : pytorch_examples
type : script
version : 1.0.0
contributor : Qi Chen
description: pytorch examples
uri : https://github.com/pytorch/examples
usage:
  parameters:
    epochs: 10
    batchsize: 32
    lr: 0.01
  roles:
    - name : worker
      command : 
        - python pytorch_examples/mnist/main.py --epochs $$epochs$$ --lr $$lr$$ --batch-size $$batchsize$$
